url: https://stevenacorrea.com
baseurl: .

# Site Settings
title: Steven A Correa
description: "The personal site of Steven Correa"
keywords: "Steven Correa, Steven A Correa, SRE, DevOps, Cloud Computing, Northern California"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/smol-bw.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
